repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort --settings-path pyproject.toml
    types: [python]
    language: system
    stages: [commit]
  - id: pyupgrade
    name: pyupgrade
    entry: poetry run pyupgrade --py37-plus
    types: [python]
    language: system
    stages: [commit]
  - id: black
    name: black
    entry: poetry run black --config pyproject.toml
    types: [python]
    language: system
    stages: [commit]
  - id: mypy_dbt_server
    name: mypy_dbt_server
    entry: poetry run mypy -p dbt_server
    require_serial: true
    types: [python]
    language: system
    stages: [push]
    pass_filenames: false
  - id: mypy_dbt_remote
    name: mypy_dbt_remote
    entry: poetry run mypy -p dbt_remote
    require_serial: true
    types: [python]
    language: system
    stages: [push]
    pass_filenames: false
