site_name: dbt-remote project
repo_name: artefactory/dbt-server
repo_url: https://github.com/artefactory/dbt-server


plugins:
  - techdocs-core

nav:
  - Home: index.md
  - dbt-remote: dbt_remote.md
  - dbt-server: dbt_server.md
  - Explanation: explanation.md
  - Advanced usage: advanced.md