name: Login to Github Container Registry and setup Docker Tag

runs:
  using: composite
  steps:

  - name: Checkout
    uses: actions/checkout@v3.0.2

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Login to Github Container Registry
    uses: docker/login-action@v1
    with:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      registry: ghcr.io

  - name: Set tag name
      id: tag
      run: echo ::set-output name=tag_name::${GITHUB_REF#*\/*\/}
      env:
        GITHUB_REF: ${{ github.ref }}
