name: dbt-remote Python package

on:
  push:
    paths:
      - api/**

jobs:

  api-test:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Get repo
        uses: actions/checkout@v3.0.2
      - name: Install Python and Poetry
        uses: ./.github/actions/poetry
     
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NB }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: '${{ secrets.SERVICE_ACCOUNT_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
          token_format: 'access_token'

      - name: Init .dbt for click execution
        run: |
          mkdir ../../../.dbt
          cp api/profiles.yml /home/runner/.dbt
          ls -la /home/runner/.dbt

      - name: Run unit tests on api/ with pytest
        run: poetry run pytest api/tests --ignore api/tests/integration

      - name: Run integration tests on api/ with pytest
        env:
            SERVICE_ACCOUNT_TOKEN: ${{ steps.auth.outputs.access_token }}
        run: poetry run pytest api/tests/integration
  
  deploy:
    runs-on: ubuntu-latest
    needs: [api-test]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NB }}/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: '${{ secrets.SERVICE_ACCOUNT_NAME }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
          token_format: 'access_token'

      # - name: Publish docker image on GCP Artifact Registry
      #   run: gcloud builds submit ./api/ --region=us-central1 --tag us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-dbt/server-image:dev
      
      # - name: Deploy docker image on Cloud Run
      #   run: gcloud run deploy server-dev --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-dbt/server-image:dev --platform managed --region us-central1 --service-account=${{ secrets.SERVICE_ACCOUNT_NAME }}@stc-dbt-test-9e19.iam.gserviceaccount.com --set-env-vars=BUCKET_NAME='dbt-stc-test' --set-env-vars=DOCKER_IMAGE='us-central1-docker.pkg.dev/stc-dbt-test-9e19/cloud-run-dbt/server-image:dev' --set-env-vars=SERVICE_ACCOUNT='${{ secrets.SERVICE_ACCOUNT_NAME }}@stc-dbt-test-9e19.iam.gserviceaccount.com' --set-env-vars=PROJECT_ID='stc-dbt-test-9e19' --set-env-vars=LOCATION='us-central1'
