name: dbt-remote Python package

on:
  push:
    paths:
      - package/**

jobs:

  package-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3.0.2
      - name: Install Python and Poetry
        uses: ./.github/actions/poetry

      - name: Init .dbt for click execution
        run: |
          mkdir ../../../.dbt
          cp api/profiles.yml /home/runner/.dbt
          ls -la /home/runner/.dbt

      - name: Test package/ with pytest
        run: poetry run pytest package/tests --ignore package/tests/integration
  
  publish:
    runs-on: ubuntu-latest
    needs: [package-test]
    steps:
      - name: Get repo
        uses: actions/checkout@v3.0.2
      - name: Install Python and Poetry
        uses: ./.github/actions/poetry
      - name: Add repository
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - name: Build package
        run: poetry build
      - name: Publish to registry
        run: poetry publish --dry-run --repository testpypi
  